// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smaefpcquzdwowlbmnls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYWVmcGNxdXpkd293bGJtbmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA3NDIsImV4cCI6MjA2NTU5Njc0Mn0.C-xSQKl6rRjQRCOwBtmQckddwBqTG7gTbFVNOoP6ba8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);